version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ads-platform-backend
    ports:
      - "3001:3001"
      - "5555:5555"  
    environment:
      - NODE_ENV=production
      - PORT=3001 
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/adsplatform
      - JWT_SECRET=${JWT_SECRET}
      - JWT_MEDIA_SECRET=${JWT_MEDIA_SECRET}
      - MEDIA_STORAGE_BASE_PATH=/var/www/media
    volumes:
      - /var/www/media:/var/www/media
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - ads-platform-network

  db:
    image: postgres:15-alpine
    container_name: ads-platform-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=adsplatform
    restart: unless-stopped
    networks:
      - ads-platform-network

networks:
  ads-platform-network:
    driver: bridge

volumes:
  postgres_data: